module.exports = {
	viewports: [
		{ name: 'phone', width: 320, height: 480 },
		{ name: 'laptop', width: 1280, height: 800 }
	],
	scenarios: [{
		label: 'Alerts',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#alerts'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Avatars',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#avatars'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Buttons',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#buttons'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Badges',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#badges'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Forms',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#forms'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Table',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#table'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	},{
		label: 'Tabs',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#tabs'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Lists',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#lists'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Cards',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#cards'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Checkboxes',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#checkbox'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Footer',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#footer'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Pagination',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#pagination'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Progress',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#progress'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'Switch',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#switch'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}, {
		label: 'typography',
		url: 'http://localhost:3000',
		hideSelectors: [],
		removeSelectors: [],
		selectors: ['#typography'],
		readyEvent: null,
		delay: 700,
		misMatchThreshold: 0.1,
		onReadyScript: null,
		onBeforeScript: null
	}],
	paths: {
		bitmaps_reference: 'visual-test',
		bitmaps_test: 'visual-test/bitmaps_test',
		casper_scripts: 'node_modules/backstopjs/.tmp/casper_scripts',
		html_report: 'visual-test/html_report',
		ci_report: 'node_modules/backstopjs/.tmp/ci_report'
	},
	engine: 'phantomjs',
	report: ['browser', 'CLI', 'CI'],
	casperFlags: [],
	debug: false,
	port: 3002
};
